### ISSUE TITLE
ModuleNotFoundError: No module named 'masif'

### ISSUE THREAD

**Issue by sirius777coder** [stebliankin/piston#2]
Great job! After installing the conda environment, I ran `python3 ./piston.py prepare -h` to test it. However, I encountered an error: `ModuleNotFoundError: No module named 'masif'`. Is there anything specific that needs to be downloaded into this conda environment?

**Comment by stebliankin** [comment]
Hello, thank you for your comment! The conda environment is sufficient to replicate the results from our research paper (see details in [PiSToN_test.ipynb](https://github.com/stebliankin/piston/blob/main/PiSToN_test.ipynb)). However, in order to execute PIsToN with new examples, it is necessary to install [MaSIF](https://github.com/LPDI-EPFL/masif) and [FireDock](http://bioinfo3d.cs.tau.ac.il/FireDock). The easiest way is to use a singularity container, as outlined in our [ReadMe](https://github.com/stebliankin/piston/tree/main#readme) and [env](https://github.com/stebliankin/piston/tree/main/env) folder.
